services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/bibliotheque
    volumes:
      - .:/app

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # AUTOMATISATION : On monte le script SQL dans le dossier spécial de Postgres
      # pour qu'il soit exécuté automatiquement à la création de la base.
      - ./data_test.sql:/docker-entrypoint-initdb.d/data_test.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bibliotheque
    ports:
      - "5433:5432"

volumes:
  postgres_data:
